### ISSUE TITLE
Invalid value "email" for "field_type", must one of "payment_link_radio" error

### ISSUE THREAD

**Issue by mario-fehr** [HubSpot/hubspot-api-php#294]
![image](https://github.com/HubSpot/hubspot-api-php/assets/14167832/8b8c0bec-009f-45ef-98cd-cb9bc7c565f9)

Looks like something is wrong with the "oneOf" shema mapping for the "field_types" at the marketing form apis.

**Comment by paulknisely** [comment]
I am receiving this error as well.

**Comment by muncherelli** [comment]
Similar error here when calling:

`$forms = $this->hubspot->marketing()->forms()->FormsApi()->getPage();`

Here is the error:

```
{
    "title": "InvalidArgumentException",
    "type": "InvalidArgumentException",
    "code": 500,
    "message": "Invalid value 'dropdown' for 'field_type', must be one of 'payment_link_radio'",
    "file": "/home/xxx/Sites/xxx/vendor/hubspot/api-client/codegen/Marketing/Forms/Model/DependentFieldDependentField.php",
    "line": 369,
    "trace": [
        {
            "file": "/home/xxx/Sites/xxx/vendor/hubspot/api-client/codegen/Marketing/Forms/ObjectSerializer.php",
            "line": 478,
            "function": "setFieldType",
            "class": "HubSpot\\Client\\Marketing\\Forms\\Model\\DependentFieldDependentField",
            "type": "->"
        },
        {
            "file": "/home/xxx/Sites/xxx/vendor/hubspot/api-client/codegen/Marketing/Forms/ObjectSerializer.php",
            "line": 369,
            "function": "deserialize",
            "class": "HubSpot\\Client\\Marketing\\Forms\\ObjectSerializer",
            "type": "::"
        },
        {
            "file": "/home/xxx/Sites/xxx/vendor/hubspot/api-client/codegen/Marketing/Forms/ObjectSerializer.php",
            "line": 478,
            "function": "deserialize",
            "class": "HubSpot\\Client\\Marketing\\Forms\\ObjectSerializer",
            "type": "::"
        },
        {
            "file": "/home/xxx/Sites/xxx/vendor/hubspot/api-client/codegen/Marketing/Forms/ObjectSerializer.php",
            "line": 369,
            "function": "deserialize",
            "class": "HubSpot\\Client\\Marketing\\Forms\\ObjectSerializer",
            "type": "::"
        },
        {
            "file": "/home/xxx/Sites/xxx/vendor/hubspot/api-client/codegen/Marketing/Forms/ObjectSerializer.php",
            "line": 478,
            "function": "deserialize",
            "class": "HubSpot\\Client\\Marketing\\Forms\\ObjectSerializer",
            "type": "::"
        },
        {
            "file": "/home/xxx/Sites/xxx/vendor/hubspot/api-client/codegen/Marketing/Forms/ObjectSerializer.php",
            "line": 369,
            "function": "deserialize",
            "class": "HubSpot\\Client\\Marketing\\Forms\\ObjectSerializer",
            "type": "::"
        },
        {
            "file": "/home/xxx/Sites/xxx/vendor/hubspot/api-client/codegen/Marketing/Forms/ObjectSerializer.php",
            "line": 478,
            "function": "deserialize",
            "class": "HubSpot\\Client\\Marketing\\Forms\\ObjectSerializer",
            "type": "::"
        },
        {
            "file": "/home/xxx/Sites/xxx/vendor/hubspot/api-client/codegen/Marketing/Forms/Api/FormsApi.php",
            "line": 1067,
            "function": "deserialize",
            "class": "HubSpot\\Client\\Marketing\\Forms\\ObjectSerializer",
            "type": "::"
        },
        {
            "file": "/home/xxx/Sites/xxx/vendor/hubspot/api-client/codegen/Marketing/Forms/Api/FormsApi.php",
            "line": 998,
            "function": "getPageWithHttpInfo",
            "class": "HubSpot\\Client\\Marketing\\Forms\\Api\\FormsApi",
            "type": "->"
        },

```

**Comment by muncherelli** [comment]
workaround:

```
$response = $this->hubspot->apiRequest([
    'path' => '/marketing/v3/forms/',
]);
$forms = json_decode($response->getBody());
```

**Comment by dimitriBouteille** [comment]
Same error with version 11.1.0 :(

**Comment by utilmind** [comment]
Receiving the same error when calling

`$client->marketing()->forms()->formsApi()->create(/* my data*/);`

It's produce the following

`PHP Fatal error:  Uncaught InvalidArgumentException: Invalid value 'email' for 'field_type', must be one of 'payment_link_radio' in /var/www/sc/sdk/vendor/hubspot/api-client/codegen/Marketing/Forms/Model/DependentFieldDependentField.php:472`

Although the form successfully created on HubSpot. Just weird fatal error that can't be caught in catch :(

**Comment by boboldehampsink** [comment]
Any updates on this?

**Comment by Skullsneeze** [comment]
I've created the above PR which should resolve this issue

**Comment by stvsimons** [comment]
Still happening in version 14.0.7: `$hubspot_client->marketing()->forms()->formsApi()->getPage(null, 1, false, ['hubspot']);` (and trying various argument differences) results in an InvalidArgumentException "Invalid value 'single_line_text' for 'field_type', must be one of 'payment_link_radio'". 

This only variation to the exception message is running the same code on a difference sandbox HS account with close to minimal forms and data the message changed to "Invalid value 'email' for 'field_type', must be one of 'payment_link_radio'". 

Tracing where the exception is thrown: Marketing/Forms/Model/FieldGroupFieldsInner.php setFieldType(), virtually everything will fail because FieldGroupFieldInner->setFieldTypesAllowableValues() returns only 1 valid type: 'payment_link_radio':
   
```
    public function setFieldType($field_type)
    {
        if (is_null($field_type)) {
            throw new \InvalidArgumentException('non-nullable field_type cannot be null');
        }
        $allowedValues = $this->getFieldTypeAllowableValues();
        if (!in_array($field_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'field_type', must be one of '%s'",
                    $field_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['field_type'] = $field_type;

        return $this;
    }
    
    public const FIELD_TYPE_PAYMENT_LINK_RADIO = 'payment_link_radio';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFieldTypeAllowableValues()
    {
        return [
            self::FIELD_TYPE_PAYMENT_LINK_RADIO,
        ];
    }
```

My fix was to expand the allowable 'field_type' values to include more than 'payment_link_radio'. In the Marketing/Forms/Model/FieldGroupFieldsInner.php file:

```
    public const FIELD_TYPE_DATEPICKER          = 'datepicker';
    public const FIELD_TYPE_DROPDOWN            = 'dropdown';
    public const FIELD_TYPE_EMAIL               = 'email';
    public const FIELD_TYPE_FILE                = 'file';
    public const FIELD_TYPE_MOBILE_PHONE        = 'mobile_phone';
    public const FIELD_TYPE_MULTI_LINE_TEXT     = 'multi_line_text';
    public const FIELD_TYPE_MULTIPLE_CHECKBOXES = 'multiple_checkboxes';
    public const FIELD_TYPE_NUMBER              = 'number';
    public const FIELD_TYPE_PAYMENT_LINK_RADIO  = 'payment_link_radio';
    public const FIELD_TYPE_PHONE               = 'phone';
    public const FIELD_TYPE_RADIO               = 'radio';
    public const FIELD_TYPE_SINGLE_CHECKBOX     = 'single_checkbox';
    public const FIELD_TYPE_SINGLE_LINE_TEXT    = 'single_line_text';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFieldTypeAllowableValues()
    {
        return [
            self::FIELD_TYPE_DATEPICKER,
            self::FIELD_TYPE_DROPDOWN,
            self::FIELD_TYPE_EMAIL,
            self::FIELD_TYPE_FILE,
            self::FIELD_TYPE_MOBILE_PHONE,
            self::FIELD_TYPE_MULTI_LINE_TEXT,
            self::FIELD_TYPE_MULTIPLE_CHECKBOXES,
            self::FIELD_TYPE_NUMBER,
            self::FIELD_TYPE_PAYMENT_LINK_RADIO,
            self::FIELD_TYPE_PHONE,
            self::FIELD_TYPE_RADIO,
            self::FIELD_TYPE_SINGLE_CHECKBOX,
            self::FIELD_TYPE_SINGLE_LINE_TEXT
        ];
    }
```

With that change, no exception is thrown and the results returned are as expected.

So annoying years now after the first report the same issue persists.

**Comment by lkaisers** [comment]
Is even anybody working on this repository??
I got the same issue still in 14.1.0. Does anybody care?
